name: asakacloud
description: A new Flutter project

# Đặt phiên bản của dự án của bạn
version: 1.0.0

# Mô tả nền tảng SDK yêu cầu
environment:
  sdk: ">=2.12.0 <3.0.0"

# Danh sách các dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3

# Danh sách các dev dependencies (tùy chọn)
dev_dependencies:
  flutter_test:
    sdk: flutter
